#
# Module manifest for module 'AzureDevOpsHelperModule'
#
# Generated by: Lars Panzerbjørn
#
# Generated on: 27/07/2025
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'AzureDevOpsHelperModule.psm1'

    # Version number of this module.
    ModuleVersion = '0.1.1'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID = '3509bf61-acf4-4889-8997-323ad32467b7'

    # Author of this module
    Author = 'Lars Panzerbjørn'

    # Company or vendor of this module
    CompanyName = 'Ordo Ursus'

    # Copyright statement for this module
    Copyright = '(c) Lars Panzerbjørn. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'This module will help with certain operations in your Azure DevOps organisation. Especially batch creating new items, or scheduling repeated tasks, pipelines etc. Feel free to get in touch via GitHub if there is anything you would like to see added.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.0'

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @()

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = 'RESTAPI','Panzerbjrn','AzureDevOps'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Panzerbjrn/AzureDevOpsHelperModule'

        }

    }

}

